// src/components/home/Home.vue
<template>
    <div class="jumbotron">
        <h2>Bienvenue</h2>
        <p>Pour en savoir plus à propos de Thibault ou Marie de Boissieu, sélectionner l'un des deux liens ci-dessous.</p>
        <div class="row home-tiles">
            <div class="col-md-6 home-tile-marie">
                <p class="app-component-header-description">Marie</p>
                <a class="app-component-header-link" routerLink="/marie" routerLinkActive="active">
                    <p class="app-component-header-text">Marie <span class="badge">Forever Living Products <br/>/ Les Créations de Marie</span></p>
                    <img src="logos/marie.svg" />
                </a>
            </div>
            <div class="col-md-6 home-tile-thibault">
                <p class="app-component-header-description">Thibault</p>
                <a class="app-component-header-link" routerLink="/thibault" routerLinkActive="active">
                    <p class="app-component-header-text">Thibault <span class="badge">Développeur Full-Stack</span></p>
                    <img src="logos/computer.svg" />
                </a>
            </div>
        </div>
    </div>
</template>

// src/app/home.component.ts
import { Component } from '@angular/core';

@Component({
    moduleId: module.id.toString(),
    selector: 'home',
    templateUrl: './home.component.html',
    styleUrls:  [ './app.component.scss', './home.component.scss' ]
})

export class HomeComponent {
}


<div class="jumbotron">
    <h2>Bienvenue</h2>
    <p>Cette page est en cours de construction.</p>
    <div class="row home-tiles">
        <div class="col-md-6 home-tile-marie">
            <a class="app-component-header-link" routerLink="/marie" routerLinkActive="active">
                <p class="app-component-header-text">Marie de Boissieu <span class="badge">Forever Living Products</span></p>
                <img src="../public/logos/logo-forever.jpg" />
            </a>
        </div>
        <div class="col-md-6 home-tile-thibault">
            <a class="app-component-header-link" routerLink="/thibault" routerLinkActive="active">
                <p class="app-component-header-text">Thibault de Boissieu <span class="badge">Développeur Full-Stack</span></p>
                <img src="../public/logos/computer.svg" />
            </a>
        </div>
    </div>
</div>
